/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f285a384-d08c-4c30-9654-d23328584b71",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_93U14N7qr",
    "aws_user_pools_web_client_id": "3vqqh105na9som5h5j15h0d4gl",
    "oauth": {}
};


export default awsmobile;
