/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2b377324-f62c-4182-b5ee-34e1579d4ae3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vQYdTVEVN",
    "aws_user_pools_web_client_id": "7o85mkmgut0bedlhn002eck5ia",
    "oauth": {}
};


export default awsmobile;
